/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminosCondicionesRouteImport } from './routes/terminos-condiciones'
import { Route as RestablecerPasswordRouteImport } from './routes/restablecer-password'
import { Route as RecuperarPasswordRouteImport } from './routes/recuperar-password'
import { Route as PoliticaTratamientoDatosRouteImport } from './routes/politica-tratamiento-datos'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrabajadorIndexRouteImport } from './routes/trabajador.index'
import { Route as PrevencionistaIndexRouteImport } from './routes/prevencionista.index'
import { Route as TrabajadorHistorialRouteImport } from './routes/trabajador.historial'
import { Route as PrevencionistaTrabajadoresRouteImport } from './routes/prevencionista.trabajadores'
import { Route as PrevencionistaSolicitudesArcoRouteImport } from './routes/prevencionista.solicitudes-arco'
import { Route as PrevencionistaReportesRouteImport } from './routes/prevencionista.reportes'
import { Route as PrevencionistaProgramacionesRouteImport } from './routes/prevencionista.programaciones'
import { Route as PrevencionistaPausasRouteImport } from './routes/prevencionista.pausas'
import { Route as PerfilConfigurarPasswordRouteImport } from './routes/perfil.configurar-password'
import { Route as AdminBootstrapRouteImport } from './routes/admin.bootstrap'
import { Route as TrabajadorPausaIdRouteImport } from './routes/trabajador.pausa.$id'
import { Route as ApiPublicHooksReconcileUsuariosRouteImport } from './routes/api/public/hooks/reconcile-usuarios'

const TerminosCondicionesRoute = TerminosCondicionesRouteImport.update({
  id: '/terminos-condiciones',
  path: '/terminos-condiciones',
  getParentRoute: () => rootRouteImport,
} as any)
const RestablecerPasswordRoute = RestablecerPasswordRouteImport.update({
  id: '/restablecer-password',
  path: '/restablecer-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarPasswordRoute = RecuperarPasswordRouteImport.update({
  id: '/recuperar-password',
  path: '/recuperar-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaTratamientoDatosRoute =
  PoliticaTratamientoDatosRouteImport.update({
    id: '/politica-tratamiento-datos',
    path: '/politica-tratamiento-datos',
    getParentRoute: () => rootRouteImport,
  } as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrabajadorIndexRoute = TrabajadorIndexRouteImport.update({
  id: '/trabajador/',
  path: '/trabajador/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrevencionistaIndexRoute = PrevencionistaIndexRouteImport.update({
  id: '/prevencionista/',
  path: '/prevencionista/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrabajadorHistorialRoute = TrabajadorHistorialRouteImport.update({
  id: '/trabajador/historial',
  path: '/trabajador/historial',
  getParentRoute: () => rootRouteImport,
} as any)
const PrevencionistaTrabajadoresRoute =
  PrevencionistaTrabajadoresRouteImport.update({
    id: '/prevencionista/trabajadores',
    path: '/prevencionista/trabajadores',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrevencionistaSolicitudesArcoRoute =
  PrevencionistaSolicitudesArcoRouteImport.update({
    id: '/prevencionista/solicitudes-arco',
    path: '/prevencionista/solicitudes-arco',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrevencionistaReportesRoute = PrevencionistaReportesRouteImport.update({
  id: '/prevencionista/reportes',
  path: '/prevencionista/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const PrevencionistaProgramacionesRoute =
  PrevencionistaProgramacionesRouteImport.update({
    id: '/prevencionista/programaciones',
    path: '/prevencionista/programaciones',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrevencionistaPausasRoute = PrevencionistaPausasRouteImport.update({
  id: '/prevencionista/pausas',
  path: '/prevencionista/pausas',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilConfigurarPasswordRoute =
  PerfilConfigurarPasswordRouteImport.update({
    id: '/configurar-password',
    path: '/configurar-password',
    getParentRoute: () => PerfilRoute,
  } as any)
const AdminBootstrapRoute = AdminBootstrapRouteImport.update({
  id: '/admin/bootstrap',
  path: '/admin/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const TrabajadorPausaIdRoute = TrabajadorPausaIdRouteImport.update({
  id: '/trabajador/pausa/$id',
  path: '/trabajador/pausa/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksReconcileUsuariosRoute =
  ApiPublicHooksReconcileUsuariosRouteImport.update({
    id: '/api/public/hooks/reconcile-usuarios',
    path: '/api/public/hooks/reconcile-usuarios',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRouteWithChildren
  '/politica-tratamiento-datos': typeof PoliticaTratamientoDatosRoute
  '/recuperar-password': typeof RecuperarPasswordRoute
  '/restablecer-password': typeof RestablecerPasswordRoute
  '/terminos-condiciones': typeof TerminosCondicionesRoute
  '/admin/bootstrap': typeof AdminBootstrapRoute
  '/perfil/configurar-password': typeof PerfilConfigurarPasswordRoute
  '/prevencionista/pausas': typeof PrevencionistaPausasRoute
  '/prevencionista/programaciones': typeof PrevencionistaProgramacionesRoute
  '/prevencionista/reportes': typeof PrevencionistaReportesRoute
  '/prevencionista/solicitudes-arco': typeof PrevencionistaSolicitudesArcoRoute
  '/prevencionista/trabajadores': typeof PrevencionistaTrabajadoresRoute
  '/trabajador/historial': typeof TrabajadorHistorialRoute
  '/prevencionista/': typeof PrevencionistaIndexRoute
  '/trabajador/': typeof TrabajadorIndexRoute
  '/trabajador/pausa/$id': typeof TrabajadorPausaIdRoute
  '/api/public/hooks/reconcile-usuarios': typeof ApiPublicHooksReconcileUsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRouteWithChildren
  '/politica-tratamiento-datos': typeof PoliticaTratamientoDatosRoute
  '/recuperar-password': typeof RecuperarPasswordRoute
  '/restablecer-password': typeof RestablecerPasswordRoute
  '/terminos-condiciones': typeof TerminosCondicionesRoute
  '/admin/bootstrap': typeof AdminBootstrapRoute
  '/perfil/configurar-password': typeof PerfilConfigurarPasswordRoute
  '/prevencionista/pausas': typeof PrevencionistaPausasRoute
  '/prevencionista/programaciones': typeof PrevencionistaProgramacionesRoute
  '/prevencionista/reportes': typeof PrevencionistaReportesRoute
  '/prevencionista/solicitudes-arco': typeof PrevencionistaSolicitudesArcoRoute
  '/prevencionista/trabajadores': typeof PrevencionistaTrabajadoresRoute
  '/trabajador/historial': typeof TrabajadorHistorialRoute
  '/prevencionista': typeof PrevencionistaIndexRoute
  '/trabajador': typeof TrabajadorIndexRoute
  '/trabajador/pausa/$id': typeof TrabajadorPausaIdRoute
  '/api/public/hooks/reconcile-usuarios': typeof ApiPublicHooksReconcileUsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRouteWithChildren
  '/politica-tratamiento-datos': typeof PoliticaTratamientoDatosRoute
  '/recuperar-password': typeof RecuperarPasswordRoute
  '/restablecer-password': typeof RestablecerPasswordRoute
  '/terminos-condiciones': typeof TerminosCondicionesRoute
  '/admin/bootstrap': typeof AdminBootstrapRoute
  '/perfil/configurar-password': typeof PerfilConfigurarPasswordRoute
  '/prevencionista/pausas': typeof PrevencionistaPausasRoute
  '/prevencionista/programaciones': typeof PrevencionistaProgramacionesRoute
  '/prevencionista/reportes': typeof PrevencionistaReportesRoute
  '/prevencionista/solicitudes-arco': typeof PrevencionistaSolicitudesArcoRoute
  '/prevencionista/trabajadores': typeof PrevencionistaTrabajadoresRoute
  '/trabajador/historial': typeof TrabajadorHistorialRoute
  '/prevencionista/': typeof PrevencionistaIndexRoute
  '/trabajador/': typeof TrabajadorIndexRoute
  '/trabajador/pausa/$id': typeof TrabajadorPausaIdRoute
  '/api/public/hooks/reconcile-usuarios': typeof ApiPublicHooksReconcileUsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/perfil'
    | '/politica-tratamiento-datos'
    | '/recuperar-password'
    | '/restablecer-password'
    | '/terminos-condiciones'
    | '/admin/bootstrap'
    | '/perfil/configurar-password'
    | '/prevencionista/pausas'
    | '/prevencionista/programaciones'
    | '/prevencionista/reportes'
    | '/prevencionista/solicitudes-arco'
    | '/prevencionista/trabajadores'
    | '/trabajador/historial'
    | '/prevencionista/'
    | '/trabajador/'
    | '/trabajador/pausa/$id'
    | '/api/public/hooks/reconcile-usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/perfil'
    | '/politica-tratamiento-datos'
    | '/recuperar-password'
    | '/restablecer-password'
    | '/terminos-condiciones'
    | '/admin/bootstrap'
    | '/perfil/configurar-password'
    | '/prevencionista/pausas'
    | '/prevencionista/programaciones'
    | '/prevencionista/reportes'
    | '/prevencionista/solicitudes-arco'
    | '/prevencionista/trabajadores'
    | '/trabajador/historial'
    | '/prevencionista'
    | '/trabajador'
    | '/trabajador/pausa/$id'
    | '/api/public/hooks/reconcile-usuarios'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/onboarding'
    | '/perfil'
    | '/politica-tratamiento-datos'
    | '/recuperar-password'
    | '/restablecer-password'
    | '/terminos-condiciones'
    | '/admin/bootstrap'
    | '/perfil/configurar-password'
    | '/prevencionista/pausas'
    | '/prevencionista/programaciones'
    | '/prevencionista/reportes'
    | '/prevencionista/solicitudes-arco'
    | '/prevencionista/trabajadores'
    | '/trabajador/historial'
    | '/prevencionista/'
    | '/trabajador/'
    | '/trabajador/pausa/$id'
    | '/api/public/hooks/reconcile-usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PerfilRoute: typeof PerfilRouteWithChildren
  PoliticaTratamientoDatosRoute: typeof PoliticaTratamientoDatosRoute
  RecuperarPasswordRoute: typeof RecuperarPasswordRoute
  RestablecerPasswordRoute: typeof RestablecerPasswordRoute
  TerminosCondicionesRoute: typeof TerminosCondicionesRoute
  AdminBootstrapRoute: typeof AdminBootstrapRoute
  PrevencionistaPausasRoute: typeof PrevencionistaPausasRoute
  PrevencionistaProgramacionesRoute: typeof PrevencionistaProgramacionesRoute
  PrevencionistaReportesRoute: typeof PrevencionistaReportesRoute
  PrevencionistaSolicitudesArcoRoute: typeof PrevencionistaSolicitudesArcoRoute
  PrevencionistaTrabajadoresRoute: typeof PrevencionistaTrabajadoresRoute
  TrabajadorHistorialRoute: typeof TrabajadorHistorialRoute
  PrevencionistaIndexRoute: typeof PrevencionistaIndexRoute
  TrabajadorIndexRoute: typeof TrabajadorIndexRoute
  TrabajadorPausaIdRoute: typeof TrabajadorPausaIdRoute
  ApiPublicHooksReconcileUsuariosRoute: typeof ApiPublicHooksReconcileUsuariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminos-condiciones': {
      id: '/terminos-condiciones'
      path: '/terminos-condiciones'
      fullPath: '/terminos-condiciones'
      preLoaderRoute: typeof TerminosCondicionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restablecer-password': {
      id: '/restablecer-password'
      path: '/restablecer-password'
      fullPath: '/restablecer-password'
      preLoaderRoute: typeof RestablecerPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-password': {
      id: '/recuperar-password'
      path: '/recuperar-password'
      fullPath: '/recuperar-password'
      preLoaderRoute: typeof RecuperarPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-tratamiento-datos': {
      id: '/politica-tratamiento-datos'
      path: '/politica-tratamiento-datos'
      fullPath: '/politica-tratamiento-datos'
      preLoaderRoute: typeof PoliticaTratamientoDatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trabajador/': {
      id: '/trabajador/'
      path: '/trabajador'
      fullPath: '/trabajador/'
      preLoaderRoute: typeof TrabajadorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prevencionista/': {
      id: '/prevencionista/'
      path: '/prevencionista'
      fullPath: '/prevencionista/'
      preLoaderRoute: typeof PrevencionistaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trabajador/historial': {
      id: '/trabajador/historial'
      path: '/trabajador/historial'
      fullPath: '/trabajador/historial'
      preLoaderRoute: typeof TrabajadorHistorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prevencionista/trabajadores': {
      id: '/prevencionista/trabajadores'
      path: '/prevencionista/trabajadores'
      fullPath: '/prevencionista/trabajadores'
      preLoaderRoute: typeof PrevencionistaTrabajadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prevencionista/solicitudes-arco': {
      id: '/prevencionista/solicitudes-arco'
      path: '/prevencionista/solicitudes-arco'
      fullPath: '/prevencionista/solicitudes-arco'
      preLoaderRoute: typeof PrevencionistaSolicitudesArcoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prevencionista/reportes': {
      id: '/prevencionista/reportes'
      path: '/prevencionista/reportes'
      fullPath: '/prevencionista/reportes'
      preLoaderRoute: typeof PrevencionistaReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prevencionista/programaciones': {
      id: '/prevencionista/programaciones'
      path: '/prevencionista/programaciones'
      fullPath: '/prevencionista/programaciones'
      preLoaderRoute: typeof PrevencionistaProgramacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prevencionista/pausas': {
      id: '/prevencionista/pausas'
      path: '/prevencionista/pausas'
      fullPath: '/prevencionista/pausas'
      preLoaderRoute: typeof PrevencionistaPausasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/configurar-password': {
      id: '/perfil/configurar-password'
      path: '/configurar-password'
      fullPath: '/perfil/configurar-password'
      preLoaderRoute: typeof PerfilConfigurarPasswordRouteImport
      parentRoute: typeof PerfilRoute
    }
    '/admin/bootstrap': {
      id: '/admin/bootstrap'
      path: '/admin/bootstrap'
      fullPath: '/admin/bootstrap'
      preLoaderRoute: typeof AdminBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trabajador/pausa/$id': {
      id: '/trabajador/pausa/$id'
      path: '/trabajador/pausa/$id'
      fullPath: '/trabajador/pausa/$id'
      preLoaderRoute: typeof TrabajadorPausaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/reconcile-usuarios': {
      id: '/api/public/hooks/reconcile-usuarios'
      path: '/api/public/hooks/reconcile-usuarios'
      fullPath: '/api/public/hooks/reconcile-usuarios'
      preLoaderRoute: typeof ApiPublicHooksReconcileUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PerfilRouteChildren {
  PerfilConfigurarPasswordRoute: typeof PerfilConfigurarPasswordRoute
}

const PerfilRouteChildren: PerfilRouteChildren = {
  PerfilConfigurarPasswordRoute: PerfilConfigurarPasswordRoute,
}

const PerfilRouteWithChildren =
  PerfilRoute._addFileChildren(PerfilRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PerfilRoute: PerfilRouteWithChildren,
  PoliticaTratamientoDatosRoute: PoliticaTratamientoDatosRoute,
  RecuperarPasswordRoute: RecuperarPasswordRoute,
  RestablecerPasswordRoute: RestablecerPasswordRoute,
  TerminosCondicionesRoute: TerminosCondicionesRoute,
  AdminBootstrapRoute: AdminBootstrapRoute,
  PrevencionistaPausasRoute: PrevencionistaPausasRoute,
  PrevencionistaProgramacionesRoute: PrevencionistaProgramacionesRoute,
  PrevencionistaReportesRoute: PrevencionistaReportesRoute,
  PrevencionistaSolicitudesArcoRoute: PrevencionistaSolicitudesArcoRoute,
  PrevencionistaTrabajadoresRoute: PrevencionistaTrabajadoresRoute,
  TrabajadorHistorialRoute: TrabajadorHistorialRoute,
  PrevencionistaIndexRoute: PrevencionistaIndexRoute,
  TrabajadorIndexRoute: TrabajadorIndexRoute,
  TrabajadorPausaIdRoute: TrabajadorPausaIdRoute,
  ApiPublicHooksReconcileUsuariosRoute: ApiPublicHooksReconcileUsuariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
