/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrabajadorRouteImport } from './routes/trabajador'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MagicLinkRouteImport } from './routes/magic-link'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrevencionistaIndexRouteImport } from './routes/prevencionista.index'
import { Route as PrevencionistaTrabajadoresRouteImport } from './routes/prevencionista.trabajadores'
import { Route as PrevencionistaProgramacionesRouteImport } from './routes/prevencionista.programaciones'
import { Route as PrevencionistaPausasRouteImport } from './routes/prevencionista.pausas'
import { Route as AdminBootstrapRouteImport } from './routes/admin.bootstrap'
import { Route as TrabajadorPausaIdRouteImport } from './routes/trabajador.pausa.$id'

const TrabajadorRoute = TrabajadorRouteImport.update({
  id: '/trabajador',
  path: '/trabajador',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MagicLinkRoute = MagicLinkRouteImport.update({
  id: '/magic-link',
  path: '/magic-link',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrevencionistaIndexRoute = PrevencionistaIndexRouteImport.update({
  id: '/prevencionista/',
  path: '/prevencionista/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrevencionistaTrabajadoresRoute =
  PrevencionistaTrabajadoresRouteImport.update({
    id: '/prevencionista/trabajadores',
    path: '/prevencionista/trabajadores',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrevencionistaProgramacionesRoute =
  PrevencionistaProgramacionesRouteImport.update({
    id: '/prevencionista/programaciones',
    path: '/prevencionista/programaciones',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrevencionistaPausasRoute = PrevencionistaPausasRouteImport.update({
  id: '/prevencionista/pausas',
  path: '/prevencionista/pausas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBootstrapRoute = AdminBootstrapRouteImport.update({
  id: '/admin/bootstrap',
  path: '/admin/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const TrabajadorPausaIdRoute = TrabajadorPausaIdRouteImport.update({
  id: '/pausa/$id',
  path: '/pausa/$id',
  getParentRoute: () => TrabajadorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/login': typeof LoginRoute
  '/magic-link': typeof MagicLinkRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/trabajador': typeof TrabajadorRouteWithChildren
  '/admin/bootstrap': typeof AdminBootstrapRoute
  '/prevencionista/pausas': typeof PrevencionistaPausasRoute
  '/prevencionista/programaciones': typeof PrevencionistaProgramacionesRoute
  '/prevencionista/trabajadores': typeof PrevencionistaTrabajadoresRoute
  '/prevencionista/': typeof PrevencionistaIndexRoute
  '/trabajador/pausa/$id': typeof TrabajadorPausaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/login': typeof LoginRoute
  '/magic-link': typeof MagicLinkRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/trabajador': typeof TrabajadorRouteWithChildren
  '/admin/bootstrap': typeof AdminBootstrapRoute
  '/prevencionista/pausas': typeof PrevencionistaPausasRoute
  '/prevencionista/programaciones': typeof PrevencionistaProgramacionesRoute
  '/prevencionista/trabajadores': typeof PrevencionistaTrabajadoresRoute
  '/prevencionista': typeof PrevencionistaIndexRoute
  '/trabajador/pausa/$id': typeof TrabajadorPausaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/login': typeof LoginRoute
  '/magic-link': typeof MagicLinkRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/trabajador': typeof TrabajadorRouteWithChildren
  '/admin/bootstrap': typeof AdminBootstrapRoute
  '/prevencionista/pausas': typeof PrevencionistaPausasRoute
  '/prevencionista/programaciones': typeof PrevencionistaProgramacionesRoute
  '/prevencionista/trabajadores': typeof PrevencionistaTrabajadoresRoute
  '/prevencionista/': typeof PrevencionistaIndexRoute
  '/trabajador/pausa/$id': typeof TrabajadorPausaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diagnostico'
    | '/login'
    | '/magic-link'
    | '/onboarding'
    | '/perfil'
    | '/trabajador'
    | '/admin/bootstrap'
    | '/prevencionista/pausas'
    | '/prevencionista/programaciones'
    | '/prevencionista/trabajadores'
    | '/prevencionista/'
    | '/trabajador/pausa/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/diagnostico'
    | '/login'
    | '/magic-link'
    | '/onboarding'
    | '/perfil'
    | '/trabajador'
    | '/admin/bootstrap'
    | '/prevencionista/pausas'
    | '/prevencionista/programaciones'
    | '/prevencionista/trabajadores'
    | '/prevencionista'
    | '/trabajador/pausa/$id'
  id:
    | '__root__'
    | '/'
    | '/diagnostico'
    | '/login'
    | '/magic-link'
    | '/onboarding'
    | '/perfil'
    | '/trabajador'
    | '/admin/bootstrap'
    | '/prevencionista/pausas'
    | '/prevencionista/programaciones'
    | '/prevencionista/trabajadores'
    | '/prevencionista/'
    | '/trabajador/pausa/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  LoginRoute: typeof LoginRoute
  MagicLinkRoute: typeof MagicLinkRoute
  OnboardingRoute: typeof OnboardingRoute
  PerfilRoute: typeof PerfilRoute
  TrabajadorRoute: typeof TrabajadorRouteWithChildren
  AdminBootstrapRoute: typeof AdminBootstrapRoute
  PrevencionistaPausasRoute: typeof PrevencionistaPausasRoute
  PrevencionistaProgramacionesRoute: typeof PrevencionistaProgramacionesRoute
  PrevencionistaTrabajadoresRoute: typeof PrevencionistaTrabajadoresRoute
  PrevencionistaIndexRoute: typeof PrevencionistaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trabajador': {
      id: '/trabajador'
      path: '/trabajador'
      fullPath: '/trabajador'
      preLoaderRoute: typeof TrabajadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magic-link': {
      id: '/magic-link'
      path: '/magic-link'
      fullPath: '/magic-link'
      preLoaderRoute: typeof MagicLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prevencionista/': {
      id: '/prevencionista/'
      path: '/prevencionista'
      fullPath: '/prevencionista/'
      preLoaderRoute: typeof PrevencionistaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prevencionista/trabajadores': {
      id: '/prevencionista/trabajadores'
      path: '/prevencionista/trabajadores'
      fullPath: '/prevencionista/trabajadores'
      preLoaderRoute: typeof PrevencionistaTrabajadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prevencionista/programaciones': {
      id: '/prevencionista/programaciones'
      path: '/prevencionista/programaciones'
      fullPath: '/prevencionista/programaciones'
      preLoaderRoute: typeof PrevencionistaProgramacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prevencionista/pausas': {
      id: '/prevencionista/pausas'
      path: '/prevencionista/pausas'
      fullPath: '/prevencionista/pausas'
      preLoaderRoute: typeof PrevencionistaPausasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bootstrap': {
      id: '/admin/bootstrap'
      path: '/admin/bootstrap'
      fullPath: '/admin/bootstrap'
      preLoaderRoute: typeof AdminBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trabajador/pausa/$id': {
      id: '/trabajador/pausa/$id'
      path: '/pausa/$id'
      fullPath: '/trabajador/pausa/$id'
      preLoaderRoute: typeof TrabajadorPausaIdRouteImport
      parentRoute: typeof TrabajadorRoute
    }
  }
}

interface TrabajadorRouteChildren {
  TrabajadorPausaIdRoute: typeof TrabajadorPausaIdRoute
}

const TrabajadorRouteChildren: TrabajadorRouteChildren = {
  TrabajadorPausaIdRoute: TrabajadorPausaIdRoute,
}

const TrabajadorRouteWithChildren = TrabajadorRoute._addFileChildren(
  TrabajadorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  LoginRoute: LoginRoute,
  MagicLinkRoute: MagicLinkRoute,
  OnboardingRoute: OnboardingRoute,
  PerfilRoute: PerfilRoute,
  TrabajadorRoute: TrabajadorRouteWithChildren,
  AdminBootstrapRoute: AdminBootstrapRoute,
  PrevencionistaPausasRoute: PrevencionistaPausasRoute,
  PrevencionistaProgramacionesRoute: PrevencionistaProgramacionesRoute,
  PrevencionistaTrabajadoresRoute: PrevencionistaTrabajadoresRoute,
  PrevencionistaIndexRoute: PrevencionistaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
